name: Score Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-22.04 ]
        php: ['7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php }} API Test
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup PHP
        uses: nanasess/setup-php@v4.0.1
        with:
          php-version: ${{ matrix.php }}
      - run: php live.php
      - name: Build Docker image 
        run: docker build . --file Dockerfile --tag cri-deploy:$(date +%s)